# Generated by Django 6.0.3 on 2026-08-10 00:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('warranty_end', models.DateField(blank=True, help_text='Fin de garantie', null=True)),
                ('operating_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=12)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'En service'), ('broken', 'En panne'), ('standby', 'Hors service')], default='ok', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MachineBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateField(default=django.utils.timezone.localdate)),
                ('resolved_at', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_breakdowns', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='machines.machine')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MachineConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('min_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit', models.CharField(choices=[('pcs', 'Pièce'), ('L', 'Litre'), ('ml', 'ml'), ('kg', 'Kg'), ('rouleau', 'Rouleau'), ('autre', 'Autre')], default='pcs', max_length=20)),
                ('needs_replacement', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='machines.machine')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MachineMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateField(default=django.utils.timezone.localdate)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('operating_hours_at', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_maintenance_logs', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='machines.machine')),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MachinePartReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=180)),
                ('replaced_at', models.DateField(default=django.utils.timezone.localdate)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('operating_hours_at', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_part_replacements', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_replacements', to='machines.machine')),
            ],
            options={
                'ordering': ['-replaced_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['status', 'is_active'], name='machines_ma_status_5d7fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['next_maintenance'], name='machines_ma_next_ma_02d5fd_idx'),
        ),
    ]
