# Generated by Django 6.0.3 on 2026-08-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='purchase_cost',
        ),
        migrations.AddField(
            model_name='machine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='machine_photos/', verbose_name='Photo de la machine'),
        ),
    ]
