# Generated by Django 6.0.3 on 2026-08-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_remove_machine_purchase_cost_machine_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='warranty_end',
        ),
        migrations.AddField(
            model_name='machinemaintenancelog',
            name='title',
            field=models.CharField(blank=True, help_text='Type ou libellé de l’intervention', max_length=180),
        ),
    ]
