# Generated by Django 6.0.3 on 2026-07-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_loginattempt_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(choices=[('metal_design', 'METAL DESIGN'), ('wood_design', 'WOOD DESIGN'), ('branding', 'BRANDING'), ('signaletique', 'Signalétique'), ('gravure', 'Gravure'), ('design_rd_innovation', 'DESIGN RD & INNOVATION')], default='metal_design', max_length=50),
        ),
    ]
