# Generated by Django 6.0.3 on 2026-07-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_org_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='org_group',
            field=models.CharField(choices=[('direction', 'Directeurs'), ('technique', 'Technique'), ('finance', 'Finance'), ('commercial', 'Commercial'), ('logistique', 'Logistique'), ('design_communication', 'Design et Communication'), ('rd', 'Recherche et Développement')], default='technique', max_length=40, verbose_name='département'),
        ),
    ]
