# Generated by Django 6.0.3 on 2026-07-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_org_group_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_guide',
            field=models.BooleanField(default=False),
        ),
    ]
