# Generated by Django 6.0.3 on 2026-08-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_phone_length_40'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='competency_profile',
            field=models.CharField(choices=[('auto', 'Auto (déduit du profil)'), ('commercial', 'Commercial'), ('finance', 'Finance'), ('logistique', 'Logistique'), ('metal_design', 'Metal Design'), ('wood_design', 'Wood Design'), ('branding', 'Design Graphique / Branding'), ('signaletique', 'Signalétique'), ('gravure', 'Gravure'), ('design_rd_innovation', 'R&D / Innovation')], default='auto', max_length=40),
        ),
    ]
