# Generated by Django 6.0.3 on 2026-07-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_technical_director_commercial_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttimeentry',
            name='entry_type',
            field=models.CharField(choices=[('work', 'Travail'), ('pause', 'Pause'), ('task', 'Tâche')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='branch',
            field=models.CharField(choices=[('metal_design', 'METAL DESIGN'), ('wood_design', 'WOOD DESIGN'), ('branding', 'BRANDING'), ('signaletique', 'Signalétique'), ('gravure', 'Gravure'), ('design_rd_innovation', 'DESIGN RD & INNOVATION')], default='metal_design', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='title',
            field=models.CharField(default='Liste de contrôle', max_length=120),
        ),
    ]
