# Generated by Django 6.0.3 on 2026-08-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_status_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='home_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Position sur l’Accueil (1 à 3). 0 = non affiché.'),
        ),
        migrations.AddField(
            model_name='project',
            name='show_on_home',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Afficher sur l’Accueil'),
        ),
    ]
