# Generated by Django 6.0.3 on 2026-08-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectassignmentnotification_type'),
        ('reports', '0010_sprint5_crm_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='reports.financeclient', verbose_name='Client CRM'),
        ),
    ]
