# Generated by Django 6.0.3 on 2026-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_sprint5_crm_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant contrat / devis accepté pour ce projet.', max_digits=12, verbose_name='Montant total du projet ($)'),
        ),
    ]
