# Generated by Django 6.0.3 on 2026-07-09 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyreport_assemblage_complete_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='department',
            field=models.CharField(blank=True, choices=[('metal_design', 'METAL DESIGN'), ('wood_design', 'WOOD DESIGN'), ('branding', 'BRANDING'), ('signaletique', 'Signalétique'), ('gravure', 'Gravure'), ('design_rd_innovation', 'DESIGN RD & INNOVATION')], max_length=50),
        ),
        migrations.CreateModel(
            name='FinanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('command_reference', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-expense_date', '-created_at'),
            },
        ),
    ]
