# Generated by Django 6.0.3 on 2026-08-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_financeincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeexpense',
            name='category',
            field=models.CharField(choices=[('materiaux', 'Matériaux / fournitures'), ('sous_traitance', 'Sous-traitance'), ('transport', 'Transport / livraison'), ('salaires', 'Salaires / primes'), ('loyer', 'Loyer / charges'), ('admin', 'Frais administratifs'), ('marketing', 'Marketing / com'), ('autre', 'Autre dépense')], default='autre', max_length=40),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('autre', 'Autre')], default='cash', max_length=40),
        ),
        migrations.AddField(
            model_name='financeincome',
            name='category',
            field=models.CharField(choices=[('acompte', 'Acompte client'), ('solde', 'Solde client'), ('prestation', 'Prestation / service'), ('autre', 'Autre encaissement')], default='autre', max_length=40),
        ),
        migrations.AddField(
            model_name='financeincome',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('autre', 'Autre')], default='cash', max_length=40),
        ),
    ]
