# Generated by Django 6.0.3 on 2026-08-06 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectassignmentnotification_type'),
        ('reports', '0005_finance_category_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeexpense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expenses', to='projects.project'),
        ),
        migrations.AddField(
            model_name='financeincome',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_incomes', to='projects.project'),
        ),
    ]
