# Generated by Django 6.0.3 on 2026-08-06 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_finance_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financeclient',
            name='commercial_owner',
            field=models.ForeignKey(blank=True, help_text='Agent commercial propriétaire du portefeuille.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_clients', to=settings.AUTH_USER_MODEL, verbose_name='Commercial responsable'),
        ),
    ]
