# Generated by Django 6.0.3 on 2026-08-06 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_crm_commercial_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financeclient',
            name='next_action',
            field=models.CharField(blank=True, max_length=255, verbose_name='Prochaine action'),
        ),
        migrations.AddField(
            model_name='financeclient',
            name='next_action_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date prochaine action'),
        ),
        migrations.AddField(
            model_name='financeclient',
            name='status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Actif'), ('inactive', 'Inactif'), ('lost', 'Perdu')], db_index=True, default='prospect', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='finance_attachments/%Y/%m/', verbose_name='Justificatif'),
        ),
        migrations.AddField(
            model_name='financeincome',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='finance_attachments/%Y/%m/', verbose_name='Justificatif'),
        ),
        migrations.CreateModel(
            name='CrmFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_type', models.CharField(choices=[('note', 'Note'), ('call', 'Appel'), ('meeting', 'RDV'), ('email', 'Email'), ('other', 'Autre')], default='note', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='reports.financeclient')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
