# Generated by Django 6.0.3 on 2026-08-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_sprint5_crm_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeclient',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Format CLI-XX-0001 (initiales commercial + numéro).', max_length=32, null=True, unique=True, verbose_name='Code client'),
        ),
    ]
